server:
  port: 8081

spring:
  profiles:
    active: local

  main:
    allow-bean-definition-overriding: true

  devtools:
    livereload:
      enabled: true

logging:
  level:
    me.sise.batch.scheduler.service: DEBUG

# feign
feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: basic

ribbon:
  eureka:
    enabled: false

trade-list-api:
  ribbon:
    listOfServers: openapi.molit.go.kr

rent-list-api:
  ribbon:
    listOfServers: openapi.molit.go.kr:8081
  api:
    key: '{cipher}3022f1a387c75a85df65ea2ad15440cdbc5f72a4c90e57262f8728b81fd3823f'
