spring:
  jpa:
    database: MYSQL
    showSql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

  datasource:
    url: '{cipher}2d17191858dd3de3c174067198f7def16ff8a823cd07c7b7a438e8523510cbd018e2f0b40fc82c8c1403317f7fb21953ee08351b41cc5c5905a1f530c4ef91f9'
    username: '{cipher}60f14de512b7f6ac4899bd14b24daae265568b1e4baadea1e97cb5570bda7618'
    password: '{cipher}24bf197c7d40c55c1ec910b48b4cebd4b301f30a94c371237c4ccd883368a6cb'
    driverClassName: org.mariadb.jdbc.Driver
    initialization-mode: NEVER
    hikari:
      maximum-pool-size: 20
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 10000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
      idle-timeout: 10000
      max-lifetime: 420000